<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Reservation;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Count how many people have reserved a dish on a particular day.
     * @param string $date the date for which to check reservations
     * @param string $dish the dish to count
     * @return integer the number of reservations
     */
    public function getNumberOfReservations($date, $dish)
    {
        $query = $this->createQueryBuilder('r')
            ->select('count(r.id)')
            ->where('r.dish = :dish AND r.menuDate = :menuDate')
            ->setParameter('menuDate', $date)
            ->setParameter('dish', $dish)
            ->getQuery();

        return $query->getSingleScalarResult();
    }

    /**
     * Find any existing reservations for a user.
     * @param string $user the user for which to find reservations
     * @param string $date the date on which to look for reservations
     * @return Reservation|null the old reservation if existing, null otherwise
     */
    public function findOldReservation($user, $date)
    {
        $query = $this->createQueryBuilder('r')
            ->where('r.userId = :userId AND r.menuDate = :menuDate')
            ->setParameter('userId', $user)
            ->setParameter('menuDate', $date)
            ->getQuery();

        return $query->setMaxResults(1)->getOneOrNullResult();
    }
}
