<?php

namespace AppBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNumberOfReservations($date, $dish)
    {
        $query = $this->createQueryBuilder('r')
            ->select('count(r.id)')
            ->where('r.dish = :dish AND r.menuDate = :menuDate')
            ->setParameter('menuDate', $date)
            ->setParameter('dish', $dish)
            ->getQuery();

        return $query->getSingleScalarResult();
    }

    public function findOldReservation($user, $date)
    {
        $query = $this->createQueryBuilder('r')
            ->where('r.userId = :userId AND r.menuDate = :menuDate')
            ->setParameter('userId', $user)
            ->setParameter('menuDate', $date)
            ->getQuery();

        return $query->setMaxResults(1)->getOneOrNullResult();
    }
}
